### ISSUE TITLE
school page management api

### ISSUE THREAD

**Issue by rrgks6221** [rrgks6221/classting-dev-task#11]
### Summary

school page management api

### description

학교 관리자는 학교를 페이지를 운영하여 학교 소식을 관리할 수 있는 api

### To-Do

- [x] 학교 페이지 생성 api
- [x] 학교 소식 생성 api
- [x] 학교 소식 수정 api
- [x] 학교 소식 삭제 api

### API

| Method | Path      | 설명           | 작업(추가, 수정, 삭제) |
| ------ | --------- | -------------- | ---------------------- |
| POST    | /api/schools | 학교 페이지 생성 | 추가                   |
| POST    | /api/schools/:schoolId/news | 학교 소식 생성 | 추가                   |
| POST    | /api/schools/:schoolId/news/:newsId | 학교 소식 수정 | 추가                   |
| POST    | /api/schools/:schoolId/news/:newsId | 학교 소식 삭제 | 추가                   |
