### ISSUE TITLE
config module setting

### ISSUE THREAD

**Issue by rrgks6221** [rrgks6221/classting-dev-task#5]
### Summary

config module 세팅 및 적용

### description

configModule 세팅 및 적용

### To-Do

- [x] configModule 세팅
- [x] config 유효성 검사
- [x] CustomConfigModule 생성 및 적용
- [x] typeorm config 분리

### API

| Method | Path      | 설명           | 작업(추가, 수정, 삭제) |
| ------ | --------- | -------------- | ---------------------- |
