### ISSUE TITLE
auth api

### ISSUE THREAD

**Issue by rrgks6221** [rrgks6221/classting-dev-task#9]
### Summary

auth api

### description

auth api 생성

### To-Do

- [x] auth api 생성
- [x] auth guard 생성
- [ ] exception filter 적용
- [x] validator 적용
- [x] swagger 적용

### API

| Method | Path      | 설명           | 작업(추가, 수정, 삭제) |
| ------ | --------- | -------------- | ---------------------- |
| GET    | /api/auth/profile | 로그인한 유저 정보 조회 | 추가                   |
| POST    | /api/auth/sign-up | 회원가입 | 추가                   |
| POST    | /api/auth/sign-in | 로그인 | 추가                   |

**Comment by rrgks6221** [comment]
exception filter 는 당장 필요하지 않기에 구현하지 않고 nestjs 내장 exception filter 사용
